"""Removed is_archived in Deadline and change nullable to True in Feedback

Revision ID: 0c6987696d09
Revises: 1677532f2bc3
Create Date: 2026-07-18 14:49:10.093557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c6987696d09'
down_revision = '1677532f2bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deadline', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('deadline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
