"""Added is_archived to Deadline

Revision ID: 1677532f2bc3
Revises: 2ab0a7d4b617
Create Date: 2026-07-18 09:02:35.170800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1677532f2bc3'
down_revision = '2ab0a7d4b617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deadline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deadline', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
