"""Added Link Model and included url in Annnouncement model

Revision ID: 19f47364080d
Revises: 13fec42029bf
Create Date: 2026-07-07 08:32:11.139171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f47364080d'
down_revision = '13fec42029bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_summary', schema=None) as batch_op:
        batch_op.drop_column('url')

    op.drop_table('link')
    # ### end Alembic commands ###
