"""renamed date_recorded to date_held

Revision ID: 24aafe8d1976
Revises: 7c544ea89ad7
Create Date: 2026-07-15 12:16:20.570584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24aafe8d1976'
down_revision = '7c544ea89ad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_held', sa.Date(), nullable=False))
        batch_op.drop_column('date_recorded')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_recorded', sa.DATETIME(), nullable=False))
        batch_op.drop_column('date_held')

    # ### end Alembic commands ###
