"""Added DeadlineCompletion model

Revision ID: 2ab0a7d4b617
Revises: c475e3e6166b
Create Date: 2026-07-18 08:46:08.878710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab0a7d4b617'
down_revision = 'c475e3e6166b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadline_completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deadline_id', sa.Integer(), nullable=False),
    sa.Column('date_completed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deadline_id'], ['deadline.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'deadline_id', name='unique_user_deadline')
    )
    with op.batch_alter_table('deadline', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deadline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.BOOLEAN(), nullable=True))

    op.drop_table('deadline_completion')
    # ### end Alembic commands ###
