"""Updated ClassSummary with schedule relationship and schedule_id

Revision ID: 49f011cc5dd6
Revises: c246b077068b
Create Date: 2026-07-15 10:51:09.991193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f011cc5dd6'
down_revision = 'c246b077068b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_summary_schedule', 'course_schedule', ['schedule_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_summary', schema=None) as batch_op:
        batch_op.drop_constraint('fk_summary_schedule', type_='foreignkey')
        batch_op.drop_column('schedule_id')

    # ### end Alembic commands ###
