"""Added instructor_email on Course model

Revision ID: 5580da778395
Revises: faab6cd27243
Create Date: 2026-07-14 19:54:52.799086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5580da778395'
down_revision = 'faab6cd27243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructor_email', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('instructor_email')

    # ### end Alembic commands ###
