"""renamed scheduled_date to date_recorded

Revision ID: 7c544ea89ad7
Revises: 49f011cc5dd6
Create Date: 2026-07-15 11:23:33.773972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c544ea89ad7'
down_revision = '49f011cc5dd6'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('class_summary', schema=None) as batch_op:
        # This tells SQLite to safely rename the column while keeping all the data inside it!
        batch_op.alter_column('scheduled_date', new_column_name='date_recorded')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_date', sa.DATETIME(), nullable=False))
        batch_op.drop_column('date_recorded')

    # ### end Alembic commands ###
