"""Removed profile tags

Revision ID: 83f5efdcc9b4
Revises: 3cc3829c4bc2
Create Date: 2026-07-17 17:08:09.965909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f5efdcc9b4'
down_revision = '3cc3829c4bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_tag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_tag', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
