"""Added scheduled_date on ClassSummary

Revision ID: a1666833245e
Revises: ac9520fa57ea
Create Date: 2026-07-07 09:21:49.371800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1666833245e'
down_revision = 'ac9520fa57ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_summary', schema=None) as batch_op:
        batch_op.drop_column('scheduled_date')

    # ### end Alembic commands ###
