"""Added date_added to announcement class and is_archived to Deadline

Revision ID: ac9520fa57ea
Revises: 19f47364080d
Create Date: 2026-07-07 08:40:03.916249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9520fa57ea'
down_revision = '19f47364080d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.Text(), nullable=True))

    with op.batch_alter_table('class_summary', schema=None) as batch_op:
        batch_op.drop_column('url')

    with op.batch_alter_table('deadline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deadline', schema=None) as batch_op:
        batch_op.drop_column('is_archived')
        batch_op.drop_column('date_added')

    with op.batch_alter_table('class_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.TEXT(), nullable=True))

    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
