"""Added room in CourseSchedule

Revision ID: c246b077068b
Revises: 5580da778395
Create Date: 2026-07-14 21:18:46.347188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c246b077068b'
down_revision = '5580da778395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room', sa.String(length=50), nullable=False, server_default='TBA'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_schedule', schema=None) as batch_op:
        batch_op.drop_column('room')

    # ### end Alembic commands ###
