"""Changed profile image avatar and added admin_reply to Feedback

Revision ID: dbd5851aec10
Revises: 0c6987696d09
Create Date: 2026-07-18 16:35:02.480978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd5851aec10'
down_revision = '0c6987696d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_reply', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('admin_reply')

    # ### end Alembic commands ###
